### ISSUE TITLE
Empty string on .env file generates undefined in environment.ts file

### ISSUE THREAD

**Issue by jcjp** [natchiketa/angular-cli-envvars#4]
# BUG
**Issue description:**
- Ts-node generates the following: ('', "", ' ', " ") as undefined in environment.ts file
- I tried using the code ${process.env.sample ? process.env.sample: ' '} the result is not an empty string but a space without the single quotes or double quotes

**Steps to reproduce**
- Make a variable inside the .env file with any of the values stated above and run the script

**Comment by Javarome** [comment]
I used this:
```
const param = process.argv[2];
const environment = param.substr(param.indexOf('=') + 1);
const environmentSuffix = environment ? `.${environment}` : '';
const targetPath = `./src/environments/environment${environmentSuffix}.ts`;
```

**Comment by jcjp** [comment]
I have moved on to another project and I can't remember my solution, I will now be closing this issue to ease the burdent of the maintainer.
