### ISSUE TITLE
Cannot find name 'process'. Do you need to install type definitions for node?

### ISSUE THREAD

**Issue by philip13** [natchiketa/angular-cli-envvars#6]
In install previously ` npm install --save @types/node`  but it show me went run ` ng serve -c dev`

```
ERROR in src/set-env.ts(29,14): error TS2580: Cannot find name 'process'. 
Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.
src/set-env.ts(30,14): error TS2580: Cannot find name 'process'. 
Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.
```

**Comment by a-vizuet** [comment]
Did you add "node" into types field in the tsconfig/tsconfig.app file?

`"types": ["node"]`

**Comment by philip13** [comment]
> Did you add "node" into types field in the tsconfig/tsconfig.app file?
> 
> `"types": ["node"]`

I added into my package.json 
```  
"devDependencies": {
    ...
    "@types/node": "~10.12.0",
...
```

Now is fixed, Thank you !

**Comment by kwhjvdkamp** [comment]
...or take care of typo's in, for instance, as I noticed, in my 'upload-batch-<script>' names, mentioned in 
> tsconfig.json: in section "include", and 
> package.json: in section "scripts". 
If a typo exists besided all other mentioned solutions this very 'not' descriptive error:
[ Cannot find name 'process'. Do you need to install type definitions for node? ] pops-up!
Yes! I had one!

**Comment by shyaaam** [comment]
For me, I had to put the `"types": ["node"]` like 

```
"compilerOptions": {
        "types": ["node"]
    }
```
in tsconfig.json file. (After installing @types/node)
